import { useState } from "react";
import { motion } from "framer-motion";
import { useLanguage } from "@/contexts/LanguageContext";
import {
  Sparkles, ChevronRight, Copy, Check, Wand2, Settings, Download,
  Shield, Terminal, Zap, ExternalLink, ToggleLeft, ToggleRight,
} from "lucide-react";

interface PromptTemplate {
  id: string;
  nameEn: string;
  nameZh: string;
  descEn: string;
  descZh: string;
  category: "query" | "trade" | "bot" | "analysis";
  skills: string[];
  mcpTools: string[];
  template: (params: PromptParams) => string;
}

interface PromptParams {
  pair: string;
  amount: string;
  mode: "demo" | "live";
  includeSkills: boolean;
  includeMCP: boolean;
  includeSafety: boolean;
}

const TEMPLATES: PromptTemplate[] = [
  {
    id: "market_query",
    nameEn: "Market Query",
    nameZh: "行情查询",
    descEn: "Real-time market data + orderbook + funding rate",
    descZh: "实时行情 + 订单簿 + 资金费率",
    category: "query",
    skills: ["market_analysis"],
    mcpTools: ["market_ticker", "market_orderbook", "market_candles", "market_funding_rate"],
    template: (p) => `# OKX AI Trading Agent — Market Query
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (SAFE)" : "--demo=false (LIVE)"}

## System Role
You are an OKX trading agent with full access to the OKX Agent Trade Kit MCP server.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Analyze market conditions using OKX V5 API data` : ""}

## Task
Get comprehensive market data for ${p.pair}.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "market_ticker", "params": { "instId": "${p.pair}" } },
  { "tool": "market_orderbook", "params": { "instId": "${p.pair}", "sz": "10" } },
  { "tool": "market_candles", "params": { "instId": "${p.pair}", "bar": "1H", "limit": "24" } }${p.pair.includes("SWAP") ? `,\n  { "tool": "market_funding_rate", "params": { "instId": "${p.pair}" } }` : ""}
]
\`\`\`

## Expected Output
- Current Price: $XX,XXX.XX
- 24h Change: ±X.XX%
- 24h Volume: $X.XB
- Top 5 Bid/Ask levels with sizes
- 24h Price Trend (from candle data)
${p.pair.includes("SWAP") ? "- Current Funding Rate: X.XXXX%\n- Next Funding Rate: X.XXXX%" : ""}

${p.includeSafety ? `## Safety\n- Mode: ${p.mode === "demo" ? "--demo (read-only, no trades)" : "--demo=false (LIVE — use sub-account)"}\n- API keys stored locally in ~/.okx/config.toml\n- Never expose API secrets in output` : ""}`,
  },
  {
    id: "trade_execution",
    nameEn: "Smart Trade",
    nameZh: "智能交易",
    descEn: "Pre-check → risk assessment → execute → verify",
    descZh: "预检查 → 风险评估 → 执行 → 验证",
    category: "trade",
    skills: ["market_analysis", "trade_execution", "risk_management"],
    mcpTools: ["market_ticker", "account_balance", "market_funding_rate", "spot_place_order", "spot_order_details"],
    template: (p) => `# OKX AI Trading Agent — Smart Trade Execution
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (SAFE)" : "--demo=false (LIVE — REAL FUNDS)"}

## System Role
You are an OKX trading agent with full access to the OKX Agent Trade Kit MCP server.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Analyze market conditions\n- trade_execution: Execute trades with pre/post checks\n- risk_management: Enforce risk limits and position sizing` : ""}

## Task
Execute a smart market buy of ${p.amount} USDT worth of ${p.pair.split("-")[0]}.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "market_ticker", "params": { "instId": "${p.pair}" }, "purpose": "Get current price" },
  { "tool": "account_balance", "params": {}, "purpose": "Verify sufficient USDT balance" },
  { "tool": "market_funding_rate", "params": { "instId": "${p.pair.replace("USDT", "USDT-SWAP")}" }, "purpose": "Check market sentiment" },
  { "tool": "market_candles", "params": { "instId": "${p.pair}", "bar": "1H", "limit": "24" }, "purpose": "Check 24h trend" },
  {
    "tool": "spot_place_order",
    "params": {
      "instId": "${p.pair}",
      "tdMode": "cash",
      "side": "buy",
      "ordType": "market",
      "sz": "${p.amount}"
    },
    "purpose": "Execute market buy",
    "condition": "Only if all pre-checks pass"
  },
  { "tool": "spot_order_details", "params": { "ordId": "{{orderId}}" }, "purpose": "Verify fill" }
]
\`\`\`

## Pre-Trade Risk Checks
1. Verify USDT balance >= ${p.amount} (abort if insufficient)
2. Check 24h price change (abort if |change| > 10%)
3. Check funding rate (abort if |rate| > 0.1%)
4. Calculate position size vs portfolio (abort if > 20%)

## Post-Trade Verification
1. Confirm order filled via spot_order_details
2. Report fill price, slippage, and total cost
3. Calculate position as % of portfolio

${p.includeSafety ? `## Safety\n- Mode: ${p.mode === "demo" ? "--demo (simulation only, no real trades)" : "--demo=false (LIVE — REAL FUNDS AT RISK)"}\n${p.mode === "live" ? "- WARNING: This will execute a REAL trade with REAL funds\n- Recommended: Use OKX sub-account with limited permissions\n- Set withdrawal whitelist and IP restrictions" : ""}\n- API keys stored locally in ~/.okx/config.toml\n- Never expose API secrets in output` : ""}`,
  },
  {
    id: "grid_bot",
    nameEn: "Grid Bot",
    nameZh: "网格机器人",
    descEn: "Analyze → configure → deploy grid trading bot",
    descZh: "分析 → 配置 → 部署网格交易机器人",
    category: "bot",
    skills: ["market_analysis", "bot_management"],
    mcpTools: ["market_ticker", "market_candles", "bot_grid_create", "bot_grid_orders", "bot_grid_positions"],
    template: (p) => `# OKX AI Trading Agent — Grid Bot Setup
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (SAFE)" : "--demo=false (LIVE)"}

## System Role
You are an OKX trading agent specializing in grid bot configuration.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Analyze volatility and price range\n- bot_management: Create and monitor trading bots` : ""}

## Task
Set up an optimal grid trading bot for ${p.pair} with ${p.amount} USDT.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "market_ticker", "params": { "instId": "${p.pair}" }, "purpose": "Get current price" },
  { "tool": "market_candles", "params": { "instId": "${p.pair}", "bar": "1D", "limit": "30" }, "purpose": "Analyze 30-day range" },
  {
    "tool": "bot_grid_create",
    "params": {
      "instId": "${p.pair}",
      "gridType": "1",
      "maxPx": "{{calculated_max}}",
      "minPx": "{{calculated_min}}",
      "gridNum": "{{calculated_grids}}",
      "totalAmt": "${p.amount}"
    },
    "purpose": "Create grid bot"
  },
  { "tool": "bot_grid_orders", "params": { "algoId": "{{algoId}}" }, "purpose": "Verify grid orders" }
]
\`\`\`

## Grid Calculation Logic
1. Get 30-day high/low from candle data
2. Set grid range: ±15% from current price (within 30d range)
3. Calculate optimal grid count based on volatility:
   - Low vol (<5% monthly): 8-12 grids
   - Med vol (5-15%): 12-20 grids
   - High vol (>15%): 20-30 grids
4. Grid spacing = (maxPx - minPx) / gridNum
5. Amount per grid = totalAmt / gridNum

## Expected Output
- Trading Pair: ${p.pair}
- Price Range: $X,XXX - $X,XXX
- Grid Count: XX
- Grid Spacing: $XX.XX
- Investment: $${p.amount}
- Amount per Grid: $XX.XX
- Estimated APY: XX-XX%

${p.includeSafety ? `## Safety\n- Mode: ${p.mode === "demo" ? "--demo (simulation only)" : "--demo=false (LIVE)"}\n- Grid bot will auto-execute trades within range\n- Set stop-loss at -10% below grid minimum\n- Monitor daily and adjust if market regime changes` : ""}`,
  },
  {
    id: "portfolio_review",
    nameEn: "Portfolio Audit",
    nameZh: "投资组合审计",
    descEn: "Full portfolio analysis + risk score + recommendations",
    descZh: "完整组合分析 + 风险评分 + 建议",
    category: "analysis",
    skills: ["market_analysis", "risk_management"],
    mcpTools: ["account_balance", "account_positions", "account_bills", "account_fee_rates"],
    template: (p) => `# OKX AI Trading Agent — Portfolio Audit
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (read-only)" : "--demo=false (read-only)"}

## System Role
You are an OKX portfolio analyst with access to the OKX Agent Trade Kit MCP server.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Cross-reference market data with positions\n- risk_management: Calculate risk metrics and generate alerts` : ""}

## Task
Perform a comprehensive portfolio audit.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "account_balance", "params": {}, "purpose": "Get all asset balances" },
  { "tool": "account_positions", "params": {}, "purpose": "Get all open positions" },
  { "tool": "account_bills", "params": { "type": "1" }, "purpose": "Get recent P&L history" },
  { "tool": "account_fee_rates", "params": { "instType": "SPOT" }, "purpose": "Check fee tier" }
]
\`\`\`

## Analysis Framework
1. **Portfolio Composition**: Asset allocation breakdown
2. **Concentration Risk**: Flag any asset > 40% of portfolio
3. **Leverage Analysis**: Check all position leverage ratios
4. **P&L Attribution**: Which positions drive returns
5. **Liquidation Risk**: Distance to liquidation for each position
6. **Fee Optimization**: Current tier and volume to next tier

## Expected Output
### Portfolio Summary
- Total Value: $XX,XXX.XX
- Available Balance: $XX,XXX.XX
- Unrealized P&L: ±$X,XXX.XX
- 7d Realized P&L: ±$X,XXX.XX

### Risk Metrics
- Risk Score: XX/100
- Max Concentration: XX% (asset)
- Average Leverage: X.Xx
- Nearest Liquidation: XX% away
- Sharpe Ratio (7d): X.XX

### Recommendations
1. [Actionable suggestion 1]
2. [Actionable suggestion 2]
3. [Actionable suggestion 3]

${p.includeSafety ? `## Safety\n- This is a READ-ONLY audit — no trades will be executed\n- API keys need only read permissions for this task\n- All data stays local` : ""}`,
  },
  {
    id: "whale_copy",
    nameEn: "Whale Copy Trade",
    nameZh: "巨鲸跟单",
    descEn: "Monitor whale activity → analyze → one-click copy",
    descZh: "监控巨鲸活动 → 分析 → 一键跟单",
    category: "trade",
    skills: ["market_analysis", "trade_execution", "risk_management"],
    mcpTools: ["market_ticker", "market_orderbook", "account_balance", "spot_place_order"],
    template: (p) => `# OKX AI Trading Agent — Whale Copy Trade
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (SAFE)" : "--demo=false (LIVE)"}

## System Role
You are an OKX whale-tracking agent that monitors large trades and executes copy trades.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Detect whale activity from orderbook depth\n- trade_execution: Execute copy trades with position sizing\n- risk_management: Limit exposure per copy trade` : ""}

## Task
Monitor ${p.pair} for whale activity and execute a scaled copy trade.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "market_ticker", "params": { "instId": "${p.pair}" }, "purpose": "Get baseline price" },
  { "tool": "market_orderbook", "params": { "instId": "${p.pair}", "sz": "50" }, "purpose": "Detect whale orders (>$100K)" },
  { "tool": "account_balance", "params": {}, "purpose": "Check available funds" },
  {
    "tool": "spot_place_order",
    "params": {
      "instId": "${p.pair}",
      "tdMode": "cash",
      "side": "{{whale_side}}",
      "ordType": "limit",
      "px": "{{whale_price}}",
      "sz": "{{scaled_size}}"
    },
    "purpose": "Copy whale trade at scaled size",
    "condition": "Only if whale detected and risk checks pass"
  }
]
\`\`\`

## Whale Detection Logic
1. Scan orderbook for orders > $100,000 in value
2. Track bid/ask ratio for directional bias
3. Monitor for sudden large market orders (volume spike)
4. If whale buy detected: copy at 1% of whale size (max $${p.amount})
5. If whale sell detected: copy at 0.5% of whale size

## Risk Controls
- Max copy trade size: $${p.amount} USDT
- Max slippage: 0.3%
- Stop-loss: -5% from entry
- Take-profit: +10% from entry
- Max 3 copy trades per hour

${p.includeSafety ? `## Safety\n- Mode: ${p.mode === "demo" ? "--demo (simulation only)" : "--demo=false (LIVE — REAL FUNDS)"}\n- Always use limit orders, never market orders for copy trades\n- Set stop-loss immediately after fill` : ""}`,
  },
  {
    id: "dca_strategy",
    nameEn: "DCA Strategy",
    nameZh: "定投策略",
    descEn: "Automated dollar-cost averaging with smart timing",
    descZh: "智能定时定额投资策略",
    category: "bot",
    skills: ["market_analysis", "trade_execution"],
    mcpTools: ["market_ticker", "market_candles", "account_balance", "spot_place_order"],
    template: (p) => `# OKX AI Trading Agent — Smart DCA Strategy
# Generated by OKX AI CORE | ${new Date().toISOString()}
# Mode: ${p.mode === "demo" ? "--demo (SAFE)" : "--demo=false (LIVE)"}

## System Role
You are an OKX DCA agent that executes intelligent dollar-cost averaging.
${p.includeSkills ? `\n## Skills Activated\n- market_analysis: Determine optimal buy timing\n- trade_execution: Execute DCA buys with verification` : ""}

## Task
Execute a smart DCA buy of $${p.amount} USDT into ${p.pair.split("-")[0]}.

## MCP Tool Sequence
\`\`\`json
[
  { "tool": "market_ticker", "params": { "instId": "${p.pair}" }, "purpose": "Get current price" },
  { "tool": "market_candles", "params": { "instId": "${p.pair}", "bar": "1D", "limit": "7" }, "purpose": "Check weekly trend" },
  { "tool": "account_balance", "params": {}, "purpose": "Verify USDT balance" },
  {
    "tool": "spot_place_order",
    "params": {
      "instId": "${p.pair}",
      "tdMode": "cash",
      "side": "buy",
      "ordType": "market",
      "sz": "${p.amount}"
    },
    "purpose": "Execute DCA buy"
  }
]
\`\`\`

## Smart DCA Logic
- If price is below 7-day average: buy 120% of standard amount
- If price is above 7-day average: buy 80% of standard amount
- If price dropped >5% in 24h: buy 150% (dip buying)
- Standard amount: $${p.amount} USDT

${p.includeSafety ? `## Safety\n- Mode: ${p.mode === "demo" ? "--demo (simulation only)" : "--demo=false (LIVE)"}\n- DCA is a long-term strategy — do not panic sell\n- Keep total DCA allocation < 30% of portfolio` : ""}`,
  },
];

export default function ClawPrompt() {
  const { t } = useLanguage();
  const [activeTemplate, setActiveTemplate] = useState("market_query");
  const [pair, setPair] = useState("BTC-USDT");
  const [amount, setAmount] = useState("100");
  const [mode, setMode] = useState<"demo" | "live">("demo");
  const [includeSkills, setIncludeSkills] = useState(true);
  const [includeMCP, setIncludeMCP] = useState(true);
  const [includeSafety, setIncludeSafety] = useState(true);
  const [copied, setCopied] = useState(false);

  const template = TEMPLATES.find((tp) => tp.id === activeTemplate)!;
  const generatedPrompt = template.template({ pair, amount, mode, includeSkills, includeMCP, includeSafety });

  const copyPrompt = () => {
    navigator.clipboard.writeText(generatedPrompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadPrompt = () => {
    const blob = new Blob([generatedPrompt], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `okx-claw-prompt-${activeTemplate}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const categoryColors: Record<string, string> = {
    query: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    trade: "text-green-400 bg-green-500/10 border-green-500/20",
    bot: "text-purple-400 bg-purple-500/10 border-purple-500/20",
    analysis: "text-orange-400 bg-orange-500/10 border-orange-500/20",
  };

  return (
    <div className="min-h-screen py-14 px-4">
      <div className="container max-w-5xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
          <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
            <Sparkles className="w-4 h-4" />
            <span>{t("Advanced", "高级")}</span>
            <ChevronRight className="w-3 h-3" />
            <span className="text-foreground">{t("Claw Prompt Generator", "Claw Prompt 生成器")}</span>
          </div>
          <h1 className="text-3xl font-[800] tracking-tight mb-3">{t("Claw-Ready Prompt Generator", "Claw-Ready Prompt 生成器")}</h1>
          <p className="text-muted-foreground">
            {t(
              "Generate complete prompts with Skills + MCP sequences + safety directives. Copy directly to Claw (Lobster Bot) or any MCP-compatible agent.",
              "生成包含Skills调用 + MCP序列 + 安全指令的完整Prompt。直接复制给Claw（龙虾Bot）或任何MCP兼容Agent。"
            )}
          </p>
        </motion.div>

        {/* Template Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 mb-6">
          {TEMPLATES.map((tp) => (
            <button
              key={tp.id}
              onClick={() => setActiveTemplate(tp.id)}
              className={`p-4 rounded-xl text-left transition-all ${
                activeTemplate === tp.id ? "glass-card border-primary/30 ring-1 ring-primary/20" : "border border-border/30 hover:border-border/60 hover:bg-accent/30"
              }`}
            >
              <div className="flex items-center gap-2 mb-2">
                <Wand2 className="w-4 h-4 text-primary" />
                <span className={`text-[10px] px-1.5 py-0.5 rounded border ${categoryColors[tp.category]}`}>
                  {tp.category.toUpperCase()}
                </span>
              </div>
              <h3 className="text-sm font-medium mb-1">{t(tp.nameEn, tp.nameZh)}</h3>
              <p className="text-[10px] text-muted-foreground line-clamp-2">{t(tp.descEn, tp.descZh)}</p>
              <div className="flex flex-wrap gap-1 mt-2">
                {tp.mcpTools.slice(0, 3).map((tool) => (
                  <span key={tool} className="text-[9px] px-1.5 py-0.5 rounded bg-accent/50 text-muted-foreground font-mono">
                    {tool}
                  </span>
                ))}
                {tp.mcpTools.length > 3 && (
                  <span className="text-[9px] px-1.5 py-0.5 rounded bg-accent/50 text-muted-foreground">
                    +{tp.mcpTools.length - 3}
                  </span>
                )}
              </div>
            </button>
          ))}
        </div>

        {/* Config Panel */}
        <div className="glass-card p-4 mb-6">
          <div className="flex items-center gap-2 mb-3">
            <Settings className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm font-medium">{t("Configuration", "配置")}</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div>
              <label className="text-xs text-muted-foreground mb-1 block">{t("Trading Pair", "交易对")}</label>
              <input
                type="text"
                value={pair}
                onChange={(e) => setPair(e.target.value.toUpperCase())}
                className="w-full px-3 py-2 rounded-lg border border-border/50 bg-background text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div>
              <label className="text-xs text-muted-foreground mb-1 block">{t("Amount (USDT)", "金额 (USDT)")}</label>
              <input
                type="text"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-border/50 bg-background text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary/30"
              />
            </div>
            <div>
              <label className="text-xs text-muted-foreground mb-1 block">{t("Mode", "模式")}</label>
              <button
                onClick={() => setMode(mode === "demo" ? "live" : "demo")}
                className={`w-full flex items-center justify-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-colors ${
                  mode === "demo"
                    ? "bg-green-500/10 text-green-400 border border-green-500/20"
                    : "bg-red-500/10 text-red-400 border border-red-500/20"
                }`}
              >
                {mode === "demo" ? <ToggleLeft className="w-4 h-4" /> : <ToggleRight className="w-4 h-4" />}
                {mode === "demo" ? "--demo (Safe)" : "--demo=false (Live)"}
              </button>
            </div>
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground block">{t("Include", "包含")}</label>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => setIncludeSkills(!includeSkills)}
                  className={`px-2 py-1 rounded text-[10px] font-medium transition-colors ${
                    includeSkills ? "bg-primary/10 text-primary border border-primary/20" : "border border-border/50 text-muted-foreground"
                  }`}
                >
                  <Zap className="w-3 h-3 inline mr-1" />Skills
                </button>
                <button
                  onClick={() => setIncludeMCP(!includeMCP)}
                  className={`px-2 py-1 rounded text-[10px] font-medium transition-colors ${
                    includeMCP ? "bg-primary/10 text-primary border border-primary/20" : "border border-border/50 text-muted-foreground"
                  }`}
                >
                  <Terminal className="w-3 h-3 inline mr-1" />MCP
                </button>
                <button
                  onClick={() => setIncludeSafety(!includeSafety)}
                  className={`px-2 py-1 rounded text-[10px] font-medium transition-colors ${
                    includeSafety ? "bg-primary/10 text-primary border border-primary/20" : "border border-border/50 text-muted-foreground"
                  }`}
                >
                  <Shield className="w-3 h-3 inline mr-1" />Safety
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Tools Used */}
        <div className="flex flex-wrap items-center gap-2 mb-4">
          <span className="text-xs text-muted-foreground">{t("MCP Tools:", "MCP工具:")}</span>
          {template.mcpTools.map((tool) => (
            <span key={tool} className="text-[10px] px-2 py-0.5 rounded-lg bg-primary/5 border border-primary/10 text-primary font-mono">
              {tool}
            </span>
          ))}
          {template.skills.length > 0 && (
            <>
              <span className="text-xs text-muted-foreground ml-2">{t("Skills:", "技能:")}</span>
              {template.skills.map((skill) => (
                <span key={skill} className="text-[10px] px-2 py-0.5 rounded-lg bg-purple-500/5 border border-purple-500/10 text-purple-400 font-mono">
                  {skill}
                </span>
              ))}
            </>
          )}
        </div>

        {/* Generated Prompt */}
        <div className="glass-card overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 border-b border-border/50">
            <div className="flex items-center gap-2">
              <span className="text-xs font-medium text-muted-foreground">{t("Generated Prompt", "生成的Prompt")}</span>
              <span className="text-[10px] px-2 py-0.5 rounded bg-accent/50 text-muted-foreground">
                {generatedPrompt.length} chars
              </span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={downloadPrompt}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border/50 text-xs text-muted-foreground hover:text-foreground transition-colors"
              >
                <Download className="w-3 h-3" />
                .md
              </button>
              <button
                onClick={copyPrompt}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 text-primary text-xs font-medium hover:bg-primary/20 transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? t("Copied!", "已复制!") : t("Copy to Claw", "复制到Claw")}
              </button>
            </div>
          </div>
          <pre className="p-6 text-xs font-mono text-foreground/80 whitespace-pre-wrap leading-relaxed max-h-[500px] overflow-y-auto">
            {generatedPrompt}
          </pre>
        </div>

        {/* Quick Presets */}
        <div className="mt-6 glass-card p-4">
          <div className="flex items-center gap-2 mb-3">
            <Zap className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium">{t("Quick Presets", "快速预设")}</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {[
              { label: "BTC Market Scan", pair: "BTC-USDT", template: "market_query", amount: "100" },
              { label: "ETH Smart Buy", pair: "ETH-USDT", template: "trade_execution", amount: "500" },
              { label: "SOL Grid Bot", pair: "SOL-USDT", template: "grid_bot", amount: "1000" },
              { label: "Portfolio Audit", pair: "BTC-USDT", template: "portfolio_review", amount: "0" },
              { label: "BTC DCA $100", pair: "BTC-USDT", template: "dca_strategy", amount: "100" },
              { label: "ETH Whale Copy", pair: "ETH-USDT", template: "whale_copy", amount: "200" },
            ].map((preset) => (
              <button
                key={preset.label}
                onClick={() => { setPair(preset.pair); setActiveTemplate(preset.template); setAmount(preset.amount); }}
                className="px-3 py-1.5 rounded-lg text-[11px] font-medium border border-border/30 text-muted-foreground hover:text-primary hover:border-primary/30 hover:bg-primary/5 transition-all"
              >
                {preset.label}
              </button>
            ))}
          </div>
        </div>

        {/* Usage Guide */}
        <div className="mt-4 p-4 rounded-xl bg-primary/5 border border-primary/10">
          <h4 className="text-sm font-semibold mb-3 flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" />
            {t("How to Use with Claw / OpenClaw", "如何配合 Claw / OpenClaw 使用")}
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 text-xs text-muted-foreground">
            <div>
              <p className="font-medium text-foreground mb-1">1. {t("Generate", "生成")}</p>
              <p>{t("Select template, configure params, prompt auto-generates.", "选择模板，配置参数，Prompt自动生成。")}</p>
            </div>
            <div>
              <p className="font-medium text-foreground mb-1">2. {t("Copy", "复制")}</p>
              <p>{t("Click 'Copy to Claw' — includes Skills + MCP + Safety.", "点击'复制到Claw' — 包含Skills + MCP + Safety。")}</p>
            </div>
            <div>
              <p className="font-medium text-foreground mb-1">3. {t("Paste & Run", "粘贴运行")}</p>
              <p>{t("Paste into Claw, Claude, Cursor, or any MCP agent.", "粘贴到Claw、Claude、Cursor或任何MCP Agent。")}</p>
            </div>
            <div>
              <p className="font-medium text-foreground mb-1">4. {t("Verify", "验证")}</p>
              <p>{t("Agent executes MCP sequence, returns TX Hash + results.", "Agent执行MCP序列，返回TX Hash + 结果。")}</p>
            </div>
          </div>
          <div className="mt-3 pt-3 border-t border-primary/10 flex items-center gap-3">
            <a href="https://github.com/okx/agent-trade-kit" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-primary hover:underline">
              <ExternalLink className="w-3 h-3" />
              Agent Trade Kit
            </a>
            <span className="text-border">|</span>
            <a href="https://www.okx.com/docs-v5/en/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-primary hover:underline">
              <ExternalLink className="w-3 h-3" />
              OKX V5 API Docs
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
